### ISSUE TITLE
Incorrect input parameter and returned value

### ISSUE THREAD

**Issue by kakarotto67** [VasulShahala/Kottans_Tasks_Lviv_2016_Shahala#1]
1. GetCreditCardVendor method should take **string** as a parameter and return vendor name also as **string**
2. IsCreditCardNumberValid method should take **string** as a parameter and return **true** or **false**
3. GenerateNextCreditCardNumber method should take **string** as a parameter and return next valid number also as **string**

**Comment by VasulShahala** [comment]
Дякую за фідбек
Спробував виправити помилки

https://github.com/VasulShahala/Kottans_Tasks_Lviv_2016_Shahala

Дякую за увагу

2016-05-07 15:34 GMT+03:00 Roman notifications@github.com:

**Comment by kakarotto67** [comment]
then please close the issue
